### ISSUE TITLE
TypeError: Cannot read property 'visitClass' of undefined

### ISSUE THREAD

**Issue by queirozfcom** [vtex-apps/docs#40]
Após a geração do esqueleto do app via `yo`, na página `avancado/melhorando-o-desenvolvimento` é dito para se rodar o webpack:

```
./node_modules/.bin/webpack
```

isso gera o seguinte erro:

```
TypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/home/vagrant/metrics-app/node_modules/babel-eslint/index.js:199:40)
    at Object.exports.parse (/home/vagrant/metrics-app/node_modules/babel-eslint/index.js:410:5)
    at parse (/home/vagrant/metrics-app/node_modules/eslint/lib/eslint.js:512:27)
    at EventEmitter.module.exports.api.verify (/home/vagrant/metrics-app/node_modules/eslint/lib/eslint.js:646:19)
    at processText (/home/vagrant/metrics-app/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/home/vagrant/metrics-app/node_modules/eslint/lib/cli-engine.js:686:26)
    at lint (/home/vagrant/metrics-app/node_modules/eslint-loader/index.js:25:20)
    at Object.module.exports (/home/vagrant/metrics-app/node_modules/eslint-loader/index.js:111:3)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/vagrant/metrics-app/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/vagrant/metrics-app/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/home/vagrant/metrics-app/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/vagrant/metrics-app/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/vagrant/metrics-app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/vagrant/metrics-app/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

Olhando pelo google parece ser por causa de [uma versão do babel-eslint](https://github.com/babel/babel-eslint/issues/243)

Não consegui resolver -- instalei a babel-eslint 4.1.8  (testei tbm a 5.0.0) e agora ele começa a fazer o build mas dá um novo erro dizendo `Unknown option: /home/vagrant/metrics-app/.babelrc.presets`:

```
(jekyll-venv)vagrant@playvm:~/metrics-app$ node_modules/.bin/webpack 
Hash: 9f7c20e0dcd130681cd5
Version: webpack 1.12.14
Time: 1000ms
               Asset       Size  Chunks             Chunk Names
           common.js    3.75 kB       0  [emitted]  common.js
    editors/index.js  253 bytes    1, 0  [emitted]  editors/index
         HomePage.js  263 bytes    2, 0  [emitted]  HomePage
       common.js.map     3.8 kB       0  [emitted]  common.js
editors/index.js.map   93 bytes    1, 0  [emitted]  editors/index
     HomePage.js.map   88 bytes    2, 0  [emitted]  HomePage
   [0] multi HomePage 28 bytes {2} [built] [1 error]
   [0] multi editors/index 28 bytes {1} [built] [1 error]
    + 2 hidden modules

ERROR in ./src/pages/HomePage/index.js
Module build failed: ReferenceError: [BABEL] /home/vagrant/metrics-app/src/pages/HomePage/index.js: Unknown option: /home/vagrant/metrics-app/.babelrc.presets
    at Logger.error (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/vagrant/metrics-app/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/vagrant/metrics-app/node_modules/babel-loader/index.js:71:12)
 @ multi HomePage

ERROR in ./src/editors/index.js
Module build failed: ReferenceError: [BABEL] /home/vagrant/metrics-app/src/editors/index.js: Unknown option: /home/vagrant/metrics-app/.babelrc.presets
    at Logger.error (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/vagrant/metrics-app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/vagrant/metrics-app/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/vagrant/metrics-app/node_modules/babel-loader/index.js:71:12)
 @ multi editors/index
```

**Comment by amoreira** [comment]
@gkozlowaski teve o mesmo erro. Como resolveu mesmo?

**Comment by queirozfcom** [comment]
@amoreira não resolvi - eu comecei a instalar via webpack pq o outro modo (manual) não estava funcionando mas depois de resolver o lance dos hooks a versão instalada manualmente voltou a funcionar então eu não tentei mais instalar via webpack.

**Comment by gkozlowaski** [comment]
@queirozfcom qual versão do generator-vtex você está usando? Resolvi esse problema com downgrade de uma subdependência `escope` para a versão 3.3.0.
Você pode fazer com `npm install --save-dev escope@3.3.0`. Na última versão do generator publicada no npm isso já está corrigido.

**Comment by queirozfcom** [comment]
@gkozlowaski agora não sei qual era a versão. Se já foi resolvido pode fechar o issue.

**Comment by tamorim** [comment]
@gkozlowaski @queirozfcom 
Opa, na verdade na última versão ainda não estava corrigido não...
Corrigi agora na versão `2.1.1`do generator.

Era o `babel-eslint` o culpado mesmo, a partir da versão `4.1.6` teve o fix disso, se eu não me engano.

Fixed on: https://github.com/vtex/generator-vtex/commit/b77f388d0034db68df29c8803ab03ae58a232515
